server:
  port: 9022
spring:
  redis:
    # Redis?????????0?
    database: 0
    host: 127.0.0.1
    port: 6379
    password: a1234567
    jedis:
      pool:
        # ????????????????????
        max-active: 8
        # ???????????????????????
        max-wait: -1
        # ???????????
        max-idle: 8
        # ?????????
        min-idle: 0
    # ??????????
    timeout: 10000
  application:
    name: jufeng-esign
###esign
esign:
  paasapi:
    url: https://smlopenapi.esign.cn
    appId: 11111111
    secret: bbbbbbbbbbbbbb
