server:
  port: 8080
  
---
show:
  id: 12  
  
---
spring:
  profiles:
    active: dev
    
---
what:
  a: a      
  
---
my:
  name: mutou(${golang.version})
#  sex: man
  age: 18


spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages,i18n/errors #国际化文件路径