spring:
  datasource:
    testDb:
      url: jdbc:mysql://localhost:3307/testDb?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
#          auto: none
#           auto: create
           auto: update
logging:
  config: classpath:log4j2.xml