server:
  port: 8001

#redis
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 39.108.191.220
    port: 6389
    password: 78ac726379a939b63544deb6dce83dd6
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
