spring:
  redis:
    database: 0
    host: 192.168.0.106
    port: 6380
    password: a1234567
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 3000
  cache:
    type: redis   # 指定使用的缓存类型
      # redis:    当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
      #   use-key-prefix: true
      #  key-prefix: "demo:"
      #  time-to-live: 60000  #缓存超时时间 单位：ms
      #  cache-null-values: false #是否缓存空值
    cache-names: user
cache:
  ttl: '{"user":60,"dept":30}'  #自定义某些缓存空间的过期时间
