spring:
  datasource:
    url: jdbc:mysql://192.168.0.106:3910/flowable?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    hikari:
      password: 123456
