spring:
  # Spring Data Redis配置
  redis:
    sentinel:
      # sentinel Master名称
      master: luo-sentinel-master
      # sentinel连接密码
      password: mypassw123456
      # sentinel节点
      nodes:
        - 192.168.3.101:26379
        - 192.168.3.102:26381
        - 192.168.3.102:26382
    # 此处设置Redis连接密码
    password: mypassw123456
    client-type: lettuce
    database: 0
    # lettuce连接池配置
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 5
        time-between-eviction-runs: 30s
        max-wait: 5s
      shutdown-timeout: 100ms